version: 3.8
service:
  movies:
    image: abhilifexsoul/paytmmoviesrepo:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
    train:
    image: abhilifexsoul/paytmtrainrepo:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
     dth:
    image: abhilifexsoul/paytmdthrepo:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
     recharge:
    image: abhilifexsoul/paytmrechargerepo:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
